language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0

before_install:
  #- export PATH="$PATH:$HOME/.composer/vendor/bin"
  #- composer global require friendsofphp/php-cs-fixer:1.*
  - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.11.6/php-cs-fixer.phar

before_script:
 - chmod +x scripts/tests/syntax.sh
 - chmod +x scripts/tests/codestyle.sh

script:
 - scripts/tests/syntax.sh
 - cat .php_cs
 - scripts/tests/codestyle.sh
